language: python
python:
  - "2.7"
before_install:
  # Download bundle of python eggs, and use it as download cache
  - "wget https://ubuntuone.com/4XDFKwxMxCLFYNxEH5B1I2 -O /tmp/geotrek-bundle.tar.gz"
  - "tar -zxf /tmp/geotrek-bundle.tar.gz --directory=$HOME"
  - echo -e "[buildout]\ndownload-cache=$HOME/.buildout/downloads" > $HOME/.buildout/default.cfg
install:
  - ./install.sh --dev
  - ./bin/buildout -Nvc buildout-tests.cfg
script: coverage run ./bin/django test authent core land maintenance trekking common infrastructure mapentity
after_success:
  # Report coverage results to coveralls.io
  - coveralls
notifications:
  email: false
  irc: "irc.freenode.org#geotrek"